apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: test-pull
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-pull 
  name: test-pull
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-pull
    weight: 100 
